services:
  postgres-db:
    image: postgres:15-alpine  
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres  
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis-db:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6379:6379"